// src/config/expressive-code.ts
export const expressiveCodeConfig = {
  styleOverrides: {
    borderColor: 'var(--sl-color-hairline)',
    borderRadius: '0.5rem',
    borderWidth: '1px',
    codeBackground: 'var(--sl-color-gray-6)',
    codeFontFamily: 'var(--font-firaCode)',
    codeFontSize: 'var(--sl-text-code-sm)',
    focusBorder: 'var(--sl-color-accent)',
    uiFontFamily: 'var(--font-inter)',
    frames: {
      copyIcon: 'var(--copy-icon)',
      frameBoxShadowCssValue: 'none',
      shadowColor: 'transparent',
      editorActiveTabBackground: 'var(--sl-color-gray-6)',
      editorActiveTabBorderColor: 'var(--sl-color-hairline)',
      editorActiveTabIndicatorTopColor: 'none',
      editorActiveTabForeground: 'var(--sl-color-text-accent)',
      editorActiveTabIndicatorBottomColor: 'var(--sl-color-accent-high)',
      editorBackground: 'var(--sl-color-gray-6)',
      editorTabBarBackground: 'var(--sl-color-gray-6)',
      editorTabBarBorderBottomColor: 'var(--sl-color-hairline)',
      editorTabBarBorderColor: 'var(--sl-color-hairline)',
      editorTabBorderRadius: '0.5rem',
      inlineButtonBackground: 'transparent',
      inlineButtonBorder: 'transparent',
      inlineButtonForeground: 'var(--sl-color-white)',
      terminalBackground: 'var(--sl-color-gray-6)',
      terminalTitlebarBackground: 'var(--sl-color-gray-6)',
      terminalTitlebarBorderBottomColor: 'var(--sl-color-hairline)',
      terminalTitlebarDotsForeground: 'var(--sl-color-gray-2)',
      terminalTitlebarDotsOpacity: '0.2',
      tooltipSuccessBackground: 'var(--sl-color-green)',
      tooltipSuccessForeground: 'var(--sl-color-text-invert)',
    },
  },
  themes: ['vitesse-black', 'vitesse-light'],
  shiki: {
    langAlias: {
      markdoc: 'mdx',
    },
  },
} as const;